version: '3.5'
services:
  faceswap:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - ENV=development
      - PORT=5000
networks:
  default:
    name: faceswap